main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

movie:
  method: 'get'
  path: movie/{id}
  controller: App\Controller\MovieController
  action: view

registration:
  method: 'get'
  path: registration
  controller: App\Controller\RegistrationController
  action: index